name: Build GTA III Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Premake
        run: ./premake5.bat
        shell: cmd

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        # Pointing to the specific folder Premake just created
        # Changed Platform to Win32 (x86) for GTA III compatibility
        run: msbuild "project_files/sky-ui.sln" /p:Configuration=Release /p:Platform=Win32

      - name: Upload ASI
        uses: actions/upload-artifact@v4
        with:
          name: SkyUI-ASI
          # This catches the file wherever it lands in the bin folder
          path: |
             bin/**/*.asi
             bin/**/*.dll
