name: Build GTA III Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 1. Download the required Plugin-SDK
      - name: Checkout Plugin-SDK
        uses: actions/checkout@v4
        with:
          repository: DK22Pac/plugin-sdk
          path: plugin-sdk

      - name: Run Premake
        run: ./premake5.bat
        shell: cmd

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        env:
          # This tells the compiler where the SDK is located
          PLUGIN_SDK_DIR: ${{ github.workspace }}\plugin-sdk
        run: msbuild "project_files/sky-ui.sln" /p:Configuration=ReleaseIII

      - name: Upload ASI
        uses: actions/upload-artifact@v4
        with:
          name: SkyUI-ASI
          path: |
             bin/**/*.asi
             bin/**/*.dll
             output/asi/*.asi
