name: Build GTA III Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout Plugin-SDK
        uses: actions/checkout@v4
        with:
          repository: DK22Pac/plugin-sdk
          path: plugin-sdk

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 1. Get the latest Premake 5 Beta
      - name: Setup Premake
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta4"

      # 2. Build the Plugin-SDK Library
      - name: Build Plugin-SDK Library
        env:
          PLUGIN_SDK_DIR: ${{ github.workspace }}\plugin-sdk
        run: |
          # We delete the old premake5.exe in the root to prevent confusion
          if exist premake5.exe del /f /q premake5.exe
          premake5 --file=plugin-sdk/tools/premake/premake5.lua vs2022
          msbuild "plugin-sdk\project_files\plugin_iii.vcxproj" /p:Configuration=Release /p:Platform=Win32
        shell: cmd

      # 3. Build Sky-UI Mod
      - name: Build Sky-UI Mod
        env:
          PLUGIN_SDK_DIR: ${{ github.workspace }}\plugin-sdk
        run: |
          premake5 vs2022
          msbuild "project_files\sky-ui.vcxproj" /p:Configuration=ReleaseIII /p:Platform=Win32
        shell: cmd

      - name: Upload ASI
        uses: actions/upload-artifact@v4
        with:
          name: SkyUI-ASI
          path: |
             output/asi/*.asi
             bin/**/*.asi
