name: Build GTA III Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout Plugin-SDK
        uses: actions/checkout@v4
        with:
          repository: DK22Pac/plugin-sdk
          path: plugin-sdk

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # We use the 'shell: cmd' but call the 'setup-msbuild' environment
      - name: Build Plugin-SDK Library
        run: |
          cd plugin-sdk/tools/premake
          premake5 vs2022
          cd ../..
          msbuild "project_files/plugin_iii.sln" /p:Configuration=Release /p:Platform=Win32
        shell: cmd

      - name: Run Sky-UI Premake
        run: ./premake5.bat
        shell: cmd

      - name: Build Sky-UI Solution
        env:
          PLUGIN_SDK_DIR: ${{ github.workspace }}\plugin-sdk
        run: msbuild "project_files/sky-ui.sln" /p:Configuration=ReleaseIII

      - name: Upload ASI
        uses: actions/upload-artifact@v4
        with:
          name: SkyUI-ASI
          path: |
             bin/**/*.asi
             output/asi/*.asi
