name: Build GTA III Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout Plugin-SDK
        uses: actions/checkout@v4
        with:
          repository: DK22Pac/plugin-sdk
          path: plugin-sdk

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Premake
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta4"

      - name: Build Everything
        env:
          PLUGIN_SDK_DIR: ${{ github.workspace }}\plugin-sdk
        run: |
          @echo off
          if exist premake5.exe del /f premake5.exe
          echo Starting SDK Generation...
          premake5 --file=plugin-sdk/tools/premake/premake5.lua vs2022
          echo Building SDK Library...
          msbuild "plugin-sdk\project_files\plugin_iii.vcxproj" /p:Configuration=Release /p:Platform=Win32 /v:m
          echo Generating SkyUI Project...
          premake5 vs2022
          echo Building SkyUI ASI...
          msbuild "project_files\sky-ui.vcxproj" /p:Configuration=ReleaseIII /p:Platform=Win32 /v:m
        shell: cmd

      - name: Upload ASI
        uses: actions/upload-artifact@v4
        with:
          name: SkyUI-ASI
          path: |
             output/asi/*.asi
             bin/**/*.asi
