name: Build GTA III Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Premake
        run: ./premake5.bat
        shell: cmd

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        # We removed /p:Platform=x86 to let it use the project's internal default
        run: msbuild "project_files/sky-ui.sln" /p:Configuration=ReleaseIII

      - name: Upload ASI
        uses: actions/upload-artifact@v4
        with:
          name: SkyUI-ASI
          path: |
             bin/**/*.asi
             bin/**/*.dll
