name: Build Sky-UI (Ultra Small)
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout Plugin-SDK
        uses: actions/checkout@v4
        with:
          repository: DK22Pac/plugin-sdk
          path: plugin-sdk

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Premake
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta4"

      - name: Build Everything
        env:
          PLUGIN_SDK_DIR: ${{ github.workspace }}\plugin-sdk
        run: |
          @echo off
          cd plugin-sdk\tools\premake
          premake5 vs2022
          cd ..\..
          msbuild "Plugin_III\Plugin_III.vcxproj" /p:Configuration=Release /p:Platform=Win32 /p:WholeProgramOptimization=true /v:m
          
          cd ..
          premake5 vs2022
          msbuild "project_files\sky-ui.vcxproj" /p:Configuration=ReleaseIII /p:Platform=Win32 /p:PostBuildEventUseInBuild=false /p:WholeProgramOptimization=true /p:Optimization=MinSpace /p:LinkIncremental=false /p:DebugInformationFormat=None /v:m
        shell: cmd

      - name: Compress with UPX
        run: |
          choco install upx
          :: Target the specific output folder and force compression
          upx --best --ultra-brute --force output/asi/*.asi
        shell: cmd

      - name: Upload ASI
        uses: actions/upload-artifact@v4
        with:
          name: SkyUI-Compressed
          path: output/asi/*.asi
